// Gabija World Package
// World content configuration overrides
//----------------------------------------------------------------------------

require "world/quests.conf"

include "/user/conf/world.conf"
