// World Shared Package
// Shared world configuration overrides
//----------------------------------------------------------------------------

require "world/instance_dungeon.conf"

include "/user/conf/world.conf"
