<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateProgramFile>false</GenerateProgramFile>
    <RootNamespace>Melia.Test.Balance</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>Test.Balance</AssemblyTitle>
    <Product>Test.Balance</Product>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <RunSettingsFilePath>$(MSBuildProjectDirectory)\Test.Balance.runsettings</RunSettingsFilePath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
    <ProjectReference Include="..\ZoneServer\ZoneServer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ExecTails.Yggdrasil" Version="2.0.7" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
