// Gabija Core Package
// World configuration overrides
//----------------------------------------------------------------------------

require "world/jobs.conf"
require "world/misc.conf"
require "world/monsters.conf"
require "world/rare_monsters.conf"

include "/user/conf/world.conf"
