// Gabija Core Package
// Configuration file
//----------------------------------------------------------------------------

// The 2016 game has class circles; its exp table gives every circle a rank
// of 15 levels.
class_circle_system: yes

// The max rank players can reach.
job_max_rank: 10

no_advancement: no
no_rank_reset: no

// The 2016 exp table ends at level 330.
max_level: 330
max_companion_level: 330

max_base_job_level: 15
max_advanced_job_level: 15

stats_per_level: 1
extra_stats_levels: 0

include "/user/conf/world/jobs.conf"
