// Gabija Core Package
// Configuration file
//----------------------------------------------------------------------------

// The 2016 game has no elite or mythic monsters.
elite_spawn_chance: 0
mythic_spawn_chance: 0

include "/user/conf/world/rare_monsters.conf"
