using System;
using System.Collections.Generic;

namespace Melia.Zone.World
{
	public sealed class WorldBossLocation
	{
		public string MapClassName { get; }
		public string MapName { get; }

		public WorldBossLocation(string mapClassName, string mapName)
		{
			this.MapClassName = mapClassName;
			this.MapName = mapName;
		}
	}

	public static class WorldBossLocations
	{
		public static readonly WorldBossLocation[] Locations =
		{
			new("f_tableland_74", "Steel Heights"),
			new("f_remains_39", "Escanciu Village"),
			new("f_tableland_28_2", "Stogas Plateau"),
			new("f_tableland_28_1", "Mesafasla"),
			new("f_tableland_72", "Sventimas Exile"),
			new("d_thorn_39_3", "Laukyme Swamp"),
			new("f_remains_38", "Goddess' Ancient Garden"),
			new("f_flash_60", "Roxona Market"),
			new("f_tableland_11_1", "Vedas Plateau"),
			new("f_tableland_71", "Grand Yard Mesa"),
			new("d_thorn_39_1", "Viltis Forest"),
			new("d_thorn_39_2", "Glade Hillroad"),
			new("f_remains_37", "Stele Road"),
			new("f_flash_59", "Verkti Square"),
			new("f_flash_61", "Ruklys Street"),
			new("f_tableland_70", "Ibre Plateau"),
			new("f_farm_49_1", "Greene Manor"),
			new("f_siauliai_46_4", "Dina Bee Farm"),
			new("f_rokas_26", "Overlong Bridge Valley"),
			new("f_rokas_24", "Gateway of the Great King"),
			new("f_orchard_32_4", "Seir Rainforest"),
			new("f_flash_63", "Downtown"),
			new("f_flash_64", "Inner Enceinte District"),
			new("f_farm_47_2", "Aqueduct Bridge Area"),
			new("f_huevillage_58_4", "Septyni Glen"),
			new("f_rokas_27", "Akmens Ridge"),
			new("f_rokas_30", "King's Plateau"),
			new("f_orchard_34_2", "Zeraha"),
			new("f_flash_29_1", "Coastal Fortress"),
			new("f_flash_58", "Dingofasil District"),
			new("f_siauliai_46_1", "Spring Light Woods"),
			new("f_farm_49_2", "Shaton Farm"),
			new("f_farm_47_3", "Myrkiti Farm"),
			new("f_farm_47_1", "Tenants' Farm"),
			new("f_huevillage_58_3", "Cobalt Forest"),
			new("f_gele_57_4", "Tenet Garden"),
			new("f_rokas_28", "Tiltas Valley"),
			new("f_orchard_34_1", "Alemeth Forest"),
			new("f_orchard_34_3", "Barha Forest"),
			new("d_thorn_19", "Gate Route"),
			new("d_thorn_21", "Kvailas Forest"),
			new("f_siauliai_47_4", "Baron Allerno"),
			new("f_huevillage_58_2", "Vieta Gorge"),
			new("f_gele_57_3", "Nefritas Cliff"),
			new("f_rokas_31", "Zachariel Crossroads"),
			new("f_bracken_63_3", "Dadan Jungle"),
			new("d_thorn_23", "Sunset Flag Forest"),
			new("d_thorn_22", "Dvasia Peak"),
			new("f_siauliai_50_1", "Gytis Settlement Area"),
			new("f_gele_57_2", "Gele Plateau"),
			new("f_pilgrimroad_49", "Genar Field"),
			new("f_rokas_25", "Ramstis Ridge"),
			new("f_bracken_63_2", "Knidos Jungle"),
			new("f_bracken_63_1", "Koru Jungle"),
			new("f_siauliai_out", "Miners' Village"),
			new("f_gele_57_1", "Srautas Gorge"),
			new("f_katyn_45_3", "Grynas Hills"),
			new("f_katyn_45_1", "Grynas Trails"),
			new("f_pilgrimroad_41_2", "Salvia Forest"),
			new("f_bracken_42_1", "Khonot Forest"),
			new("f_siauliai_11_re", "(Ex)Paupys Crossing"),
			new("f_siauliai_west", "West Siauliai Woods"),
			new("f_3cmlake_84", "Absenta Reservoir"),
			new("f_3cmlake_83", "Pelke Shrine Ruins"),
			new("f_katyn_45_2", "Grynas Training Camp"),
			new("f_pilgrimroad_41_4", "Sekta Forest"),
			new("f_pilgrimroad_41_3", "Rasvoy Lake"),
			new("f_whitetrees_56_1", "Mishekan Forest"),
			new("f_siauliai_15_re", "(Ex)Woods of the Linked Bridges"),
			new("f_katyn_13", "Poslinkis Forest"),
			new("f_katyn_12", "Letas Stream"),
			new("f_pilgrimroad_41_5", "Ouaas Memorial"),
			new("f_maple_24_3", "Northern Parias Forest"),
			new("f_whitetrees_22_3", "Izoliacjia Plateau"),
			new("f_katyn_7_2", "Owl Burial Ground"),
			new("f_katyn_13_3", "Arrow Path"),
			new("f_maple_24_1", "Central Parias Forest"),
			new("f_whitetrees_23_3", "Syla Forest"),
			new("f_whitetrees_21_2", "Nobreer Forest"),
			new("f_maple_24_2", "Southern Parias Forest"),
			new("f_maple_23_2", "Pystis Forest"),
			new("f_whitetrees_23_1", "Emmet Forest"),
			new("d_prison_78", "Kalejimas Visiting Room"),
			new("d_prison_79", "Storage"),
			new("d_prison_80", "Solitary Cells"),
			new("d_prison_81", "Workshop"),
			new("d_prison_82", "Investigation Room"),
			new("d_catacomb_80_1", "Rancid Labyrinth"),
			new("d_catacomb_80_2", "Balaam Camp Site"),
			new("d_catacomb_80_3", "Michmas Temple"),
			new("d_abbey_39_4", "Tyla Monastery"),
			new("d_underfortress_65", "Sentry Bailey"),
			new("d_underfortress_66", "Drill Ground of Confliction"),
			new("d_underfortress_67", "Resident Quarter"),
			new("d_underfortress_68", "Storage Quarter"),
			new("d_underfortress_30_1", "Ruklys Hall of Fame"),
			new("d_underfortress_30_2", "Extension"),
			new("d_underfortress_30_3", "Evacuation Residential District"),
			new("d_underfortress_69", "Fortress Battlegrounds"),
			new("d_velniasprison_51_1", "Demon Prison District 1"),
			new("d_velniasprison_51_2", "Demon Prison District 2"),
			new("d_velniasprison_51_3", "Demon Prison District 4"),
			new("d_velniasprison_51_4", "Demon Prison District 3"),
			new("d_velniasprison_51_5", "Demon Prison District 5"),
			new("d_firetower_41", "Mage Tower 1F"),
			new("d_firetower_42", "Mage Tower 2F"),
			new("d_firetower_43", "Mage Tower 3F"),
			new("d_firetower_44", "Mage Tower 4F"),
			new("d_firetower_45", "Mage Tower 5F"),
			new("d_chapel_57_5", "Tenet Church B1"),
			new("d_chapel_57_6", "Tenet Church 1F"),
			new("d_chapel_57_7", "Tenet Church 2F"),
			new("id_catacomb_01", "Guards Graveyard"),
			new("d_zachariel_32", "Royal Mausoleum 1F"),
			new("d_zachariel_33", "Royal Mausoleum 2F"),
			new("d_zachariel_34", "Royal Mausoleum 3F"),
			new("d_zachariel_35", "Royal Mausoleum 4F"),
			new("d_zachariel_36", "Royal Mausoleum 5F"),
			new("d_abbey_64_1", "(Closed) Novaha Assembly Hall"),
			new("d_abbey_64_2", "(Closed) Novaha Annex"),
			new("d_abbey_64_3", "(Closed) Novaha Institute"),
			new("d_cmine_01", "Crystal Mine 1F"),
			new("d_cmine_02", "Crystal Mine 2F"),
			new("d_cmine_6", "Crystal Mine 3F"),
			new("d_cmine_8", "Crystal Mine Lot 2 - 1F"),
			new("d_cmine_9", "Crystal Mine Lot 2 - 2F"),
			new("d_limestonecave_52_1", "Tevhrin Stalactite Cave Section 1"),
			new("d_limestonecave_52_2", "Tevhrin Stalactite Cave Section 2"),
			new("d_limestonecave_52_3", "Tevhrin Stalactite Cave Section 3"),
			new("d_limestonecave_52_4", "Tevhrin Stalactite Cave Section 4"),
			new("d_limestonecave_52_5", "Tevhrin Stalactite Cave Section 5"),
			new("d_prison_62_1", "(Closed) Ashaq Underground Prison 1F"),
			new("d_prison_62_2", "(Closed) Ashaq Underground Prison 2F"),
			new("d_prison_62_3", "(Closed) Ashaq Underground Prison 3F"),
			new("id_catacomb_33_1", "(Closed) Sienakal Graveyard"),
			new("id_catacomb_33_2", "(Closed) Carlyle's Mausoleum"),
			new("d_abbey_41_6", "Maven Abbey"),
			new("d_abbey_22_4", "Narvas Temple"),
			new("d_abbey_22_5", "Narvas Temple Annex"),
			new("d_fantasylibrary_48_1", "Sausis Room 9"),
			new("d_fantasylibrary_48_2", "Sausis Room 10"),
			new("d_fantasylibrary_48_3", "Valandis Room 2"),
			new("d_fantasylibrary_48_4", "Valandis Room 3"),
			new("d_fantasylibrary_48_5", "Valandis Room 91"),
		};

		public static WorldBossLocation GetRandom(Random random)
		{
			if (Locations.Length == 0)
				throw new InvalidOperationException("World Boss location pool is empty.");

			return Locations[random.Next(Locations.Length)];
		}
	}
}
