// Melia
// Configuration file
//----------------------------------------------------------------------------

// Opens a tutorial window by its class name
tutorial: 50,50

// Resets all tutorials seen on the account
resettutorials: 50,50
