ALTER TABLE `buffs` ADD COLUMN `numArg3` INT(11) NOT NULL DEFAULT '0' AFTER `numArg2`;
ALTER TABLE `buffs` ADD COLUMN `numArg4` INT(11) NOT NULL DEFAULT '0' AFTER `numArg3`;
ALTER TABLE `buffs` ADD COLUMN `numArg5` INT(11) NOT NULL DEFAULT '0' AFTER `numArg4`;