// Laima World Package
// World content configuration overrides
//----------------------------------------------------------------------------

require "world/minigames.conf"

include "/user/conf/world.conf"
