// Laima World Package
// World content configuration overrides
//----------------------------------------------------------------------------

require "world/boss_monsters.conf"
require "world/minigames.conf"
require "world/quests.conf"
require "world/rare_monsters.conf"

include "/user/conf/world.conf"
