// Laima World Package
// Laima's world: NPCs, monster spawns, warps, quests, treasures and minigames.
//---------------------------------------------------------------------------

name        : laima-world
type        : world
description : Laima world - NPCs, spawns, warps, quests, treasures and minigames
version     : 1.0.0
