//--- Melia Script ----------------------------------------------------------
// Combat Calculation Script
//--- Description -----------------------------------------------------------
// Functions that calculate item-related values, such as generate options.
//---------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Melia.Shared.Data.Database;
using Melia.Shared.Game.Const;
using Melia.Shared.Network;
using Melia.Zone;
using Melia.Zone.Buffs.Handlers;
using Melia.Zone.Buffs.Handlers.Swordsman.Highlander;
using Melia.Zone.Network;
using Melia.Zone.Scripting;
using Melia.Zone.Skills;
using Melia.Zone.Skills.Combat;
using Melia.Zone.World.Actors;
using Melia.Zone.World.Actors.Characters;
using Melia.Zone.World.Actors.Characters.Components;
using Melia.Zone.World.Actors.CombatEntities.Components;
using Melia.Zone.World.Actors.Monsters;
using Melia.Zone.World.Items;
using Yggdrasil.Extensions;
using Yggdrasil.Logging;
using Yggdrasil.Util;

public class ItemCalculationsScript : GeneralScript
{
	/// <summary>
	/// Returns the amount of SP spent when using the skill.
	/// </summary>
	/// <param name="item"></param>
	/// <returns></returns>
	//[ScriptableFunction]
	public float SCR_Get_ItemAttack(Item item)
	{
		return 0;
		//return value;
	}

	/// <summary>
	/// Returns an item's base stat value
	/// </summary>
	/// <param name="item"></param>
	/// <param name="dataValue"></param>
	/// <returns></returns>
	private float GetBasicValue(Item item, float dataValue)
	{
		if (string.IsNullOrEmpty(item.Data.EquipSlot))
			return 0;

		var changeBasicProp = item.Properties.GetFloat(PropertyName.ChangeBasicPropValue);
		var basicValue = changeBasicProp > 0 ? changeBasicProp : dataValue;

		return basicValue * this.GetGradeRatio(item);
	}

	/// <summary>
	/// Returns the multiplier an item's grade puts on its base attack and
	/// defense, where Normal is 1.
	/// </summary>
	/// <remarks>
	/// basicRatio in item_grades.txt is 100 / 105 / 110 / 115 / 120 / 125 from
	/// Normal to Goddess, so a grade is worth five percent of an item's base
	/// attack and defense.
	///
	/// The ratio is relative to the grade the item's own row carries, not to
	/// Normal, and that is what keeps the server and the client agreeing.
	/// items.txt is generated by running the client's own RefreshScp and
	/// reading the MINATK / MAXATK / DEF it produces, and that script already
	/// multiplies by the row's grade - so the exported number is that item at
	/// that grade, not a Normal baseline. Scaling it by the absolute ratio
	/// would count the grade twice for every item in the game. Dividing it out
	/// first leaves an item at its own grade reading exactly what was exported
	/// and an upgraded one reading the step between the two grades, which is
	/// the same number the client's tooltip computes from the live ItemGrade
	/// property.
	///
	/// Reinforce is applied to the graded value by every caller, so a refined
	/// high-grade piece pulls ahead on both terms rather than only on the base.
	/// </remarks>
	/// <param name="item"></param>
	/// <returns></returns>
	private float GetGradeRatio(Item item)
	{
		if (!item.Properties.TryGetFloat(PropertyName.ItemGrade, out var grade))
			return 1f;

		var current = this.GetBasicRatio((int)grade);
		var exported = this.GetBasicRatio((int)item.Data.Grade);

		if (current <= 0 || exported <= 0)
			return 1f;

		return current / exported;
	}

	/// <summary>
	/// Returns the base stat ratio of one item grade, or zero when the grade
	/// has no row.
	/// </summary>
	/// <param name="grade"></param>
	/// <returns></returns>
	private float GetBasicRatio(int grade)
	{
		if (!ZoneServer.Instance.Data.ItemGradeDb.TryFindByGrade(grade, out var gradeData))
			return 0;

		return gradeData.BasicRatio;
	}

	[ScriptableFunction]
	public float SCR_Get_Item_MAXATK(Item item)
	{
		var maxAtk = this.GetBasicValue(item, item.Data.MaxAtk);
		if (maxAtk <= 0)
			return 0;

		//Log.Debug("Calculated Max ATK: {0}", maxAtk);
		return MathF.Round(maxAtk + GetReinforceAddValue(item, PropertyName.ATK, maxAtk), MidpointRounding.AwayFromZero);
	}



	[ScriptableFunction]
	public float SCR_Get_Item_MINATK(Item item)
	{
		var minAtk = this.GetBasicValue(item, item.Data.MinAtk);
		if (minAtk <= 0)
			return 0;

		//Log.Debug("Calculated Min ATK: {0} + {1}", minAtk, GetReinforceAddValue(item, PropertyName.ATK, minAtk));
		return MathF.Round(minAtk + GetReinforceAddValue(item, PropertyName.ATK, minAtk), MidpointRounding.AwayFromZero);
	}

	[ScriptableFunction]
	public float SCR_Get_Item_MATK(Item item)
	{
		var itemATK = this.GetBasicValue(item, item.Data.MAtk);
		if (itemATK <= 0)
			return 0;

		//Log.Debug("Calculated MATK: {0}", itemATK);
		return MathF.Round(itemATK + GetReinforceAddValue(item, PropertyName.MATK, itemATK), MidpointRounding.AwayFromZero);
	}

	/// <summary>
	/// Calculate an item's DEF
	/// </summary>
	/// <param name="item"></param>
	/// <returns></returns>
	[ScriptableFunction]
	public float SCR_Get_Item_DEF(Item item)
	{
		var basicDef = this.GetBasicValue(item, item.Data.Def);
		if (basicDef <= 0)
			return 0;

		basicDef = MathF.Floor(basicDef);
		//Log.Debug("Calculated DEF: {0}", basicDef);
		return MathF.Floor(basicDef + GetReinforceAddValue(item, PropertyName.DEF, basicDef));
	}

	/// <summary>
	/// Calculate an item's MDEF
	/// </summary>
	/// <param name="item"></param>
	/// <returns></returns>
	[ScriptableFunction]
	public float SCR_Get_Item_MDEF(Item item)
	{
		var basicMDef = this.GetBasicValue(item, item.Data.MDef);
		if (basicMDef <= 0)
			return 0;

		basicMDef = MathF.Floor(basicMDef);
		//Log.Debug("Calculated MDEF: {0}", basicMDef);
		return MathF.Floor(basicMDef + GetReinforceAddValue(item, PropertyName.MDEF, basicMDef));
	}

	/// <summary>
	/// Calculate an item's repair cost based on
	/// equipment type, level, and rank.
	/// </summary>
	[ScriptableFunction]
	public float SCR_Get_Item_RepairPrice(Item item)
	{
		// Base price
		var basePrice = 100f;

		// Level multiplier calculation (smoothed exponential-to-linear curve)
		var level = item.UseLevel;
		var baseMultiplier = 1f;
		var exponentialFactor = 0.04f;
		var linearFactor = 25f;
		var transitionLevel = 100f;
		var transitionSmoothness = 50f;

		var exponentialPart = Math.Pow(1 + exponentialFactor, level);
		var linearPart = 1 + (level / linearFactor);
		var transitionFactor = 1 / (1 + Math.Exp(-(level - transitionLevel) / transitionSmoothness));
		var levelMultiplier = baseMultiplier * ((float)exponentialPart * (1 - (float)transitionFactor) + (float)linearPart * (float)transitionFactor);

		// Grade multiplier (20% per grade linear increase)
		var itemGrade = (int)item.Properties.GetFloat(PropertyName.ItemGrade);
		var gradeMultiplier = 1 + (itemGrade - 1) * 0.2f;

		// Type multiplier
		var typeMultiplier = 1.0f;
		var equipType = item.Data.Group;
		switch (equipType)
		{
			case ItemGroup.Weapon:
				typeMultiplier = 1.5f;
				break;
			case ItemGroup.SubWeapon:
				typeMultiplier = 1.4f;
				break;
			case ItemGroup.Armor:
				typeMultiplier = 1.2f;
				break;
		}

		// Calculate final repair cost
		var repairCost = basePrice * levelMultiplier * gradeMultiplier * typeMultiplier;

		// Round down to nearest integer
		return (float)Math.Floor(repairCost);
	}

	[ScriptableFunction]
	public float SCR_Get_Item_SocketPrice(Item item)
	{
		// Get the item level and grade
		var itemLevel = item.UseLevel;
		if (itemLevel <= 0)
			return 0;

		if (!item.Properties.TryGetFloat(PropertyName.ItemGrade, out var grade))
			return 0;

		// Get current socket count
		var currentSockets = item.GetUsedSockets();

		// Define grade ratios as per Lua implementation
		float[] gradeRatios = { 1.2f, 1f, 0.5f, 0.4f, 0.3f, 0.1f };

		// Calculate grade multiplier
		var itemGradeRatio = 1f;
		var priceMultiplier = 2f;
		var basePrice = 10000;

		if (currentSockets >= 1)
		{
			// Adjust grade index to 0-based for C# array
			var gradeIndex = (int)grade - 1;
			if (gradeIndex >= 0 && gradeIndex < gradeRatios.Length)
				itemGradeRatio = gradeRatios[gradeIndex];
		}

		// Find the base socket price from the socket price database
		var socketPriceDb = ZoneServer.Instance.Data.SocketPriceDb;
		if (socketPriceDb == null)
			return 0;

		foreach (var priceData in socketPriceDb.Entries.Values)
		{
			if (priceData.ItemLevel == itemLevel)
			{
				var priceRatio = currentSockets + 1;
				// Calculate final price using the same formula as Lua
				// In Lua: cls.NewSocketPrice * secretNumber * (priceRatio ^ (1 / itemGradeRatio))
				var finalPrice = basePrice + priceData.AddPrice *
							 priceMultiplier *
							 ((float)Math.Pow(priceRatio, 2) / itemGradeRatio);

				return (float)Math.Floor(finalPrice);
			}
		}

		return 0;
	}

	/// <summary>
	/// Gain per reinforce level, as a ratio of the item's own base value.
	/// </summary>
	private const float ReinforceGainPerLevel = 0.035f;

	public float GetReinforceAddValue(Item item, string prop, float basicValue)
	{
		var basicTooltipProp = item.Data.MainProperties;

		if (string.IsNullOrEmpty(basicTooltipProp) || !basicTooltipProp.Contains(prop))
			return 0;

		var lv = item.Level;
		if (lv <= 0) return 0;

		if (basicValue <= 0)
			return 0;

		if (!item.Properties.TryGetFloat(PropertyName.Reinforce_2, out var reinforceValue))
			return 0;

		var reinforceRatio = item.Properties.GetFloat(PropertyName.ReinforceRatio, 100);

		var value = basicValue * reinforceValue * ReinforceGainPerLevel;
		value *= (reinforceRatio / 100);

		return (float)Math.Floor(value);
	}


	[ScriptableFunction]
	public float SCR_Get_Item_AppraisalPrice(Item item)
	{
		var sellPrice = item.Data.SellPrice;
		// Get the item level and grade
		var level = item.UseLevel;
		if (level <= 0)
			return 0;

		if (!item.Properties.TryGetFloat(PropertyName.ItemGrade, out var grade))
			return 0;

		// Default price ratio 
		var priceRatio = 10;

		// Calculate the base sell price if not provided
		if (sellPrice == 0)
		{
			if (grade <= 2)
			{
				sellPrice = level * priceRatio;
			}
			else if (grade > 2)
			{
				sellPrice = (int)Math.Floor(level * priceRatio * 1.5);
			}
			else
			{
				return 0;
			}
		}

		return sellPrice;
	}
}
